{{- if .Values.monitoring.grafana }}
{{- if and .Values.volumes.persistence .Values.grafana.volumes.persistence }}
{{- if not (or .Values.grafana.volumes.data.storageClass .Values.grafana.volumes.data.storageClassName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "pulsar.grafana.volumes.pvc.name" . }}"
  namespace: {{ template "pulsar.namespace" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.grafana.volumes.data.size }}
  accessModes: [ "ReadWriteOnce" ]
{{- if  .Values.grafana.volumes.data.storageClass }}
  storageClassName: "{{ template "pulsar.grafana.volumes.pvc.name" . }}}"
{{- else if .Values.grafana.volumes.data.storageClassName }}
  storageClassName: {{ .Values.grafana.volumes.data.storageClassName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}