#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if and .Values.initialize (not .Values.broker.operator.enabled) }}
{{- if .Values.components.broker }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_metadata.component }}
spec:
  template:
    spec:
      initContainers:
      {{- if .Values.pulsar_metadata.configurationStore }}
      - name: wait-cs-ready
        image: "{{ .Values.images.pulsar_metadata.image.repository }}:{{ .Values.images.pulsar_metadata.image.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar_metadata.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            until nslookup {{ .Values.pulsar_metadata.configurationStore}}; do
              sleep 3;
            done;

      {{- end }}
      - name: wait-zookeeper-ready
        image: "{{ .Values.images.pulsar_metadata.repository }}:{{ .Values.images.pulsar_metadata.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar_metadata.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            {{- if $zk:=.Values.pulsar_metadata.userProvidedZookeepers }}
            until bin/pulsar zookeeper-shell -server {{ $zk }} ls {{ or .Values.metadataPrefix "/" }}; do
              echo "user provided zookeepers {{ $zk }} are unreachable... check in 3 seconds ..." && sleep 3;
            done;
            {{ else }}
            until nslookup {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ add (.Values.zookeeper.replicaCount | int) -1 }}.{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}.{{ template "pulsar.namespace" . }}; do
              sleep 3;
            done;
            {{- end}}
      {{- if .Values.zookeeper.customTools.restore.enable }}
      - name: pulsar-metadata-cleanup
        image: "{{ .Values.images.zookeeper.customTools.restore.repository }}:{{ .Values.images.zookeeper.customTools.restore.tag }}"
        imagePullPolicy: "{{ .Values.images.zookeeper.customTools.restore.pullPolicy }}"
        command: ["sh", "-c"]
        args:
          - >
            {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 12 }}
            {{ if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
            export "$(cat conf/pulsar_env.sh | xargs)";
            export "OPTS=${PULSAR_EXTRA_OPTS}";
            env;
            {{- end }}
            bin/pulsar-metadata-tool cleanup
        env:
          - name: METADATA_TOOL_CONF
            value: "/pulsar-metadata-tool/conf/pulsar-metadata-tool/pulsar-metadata-tool.properties"
        volumeMounts:
          - name: cleanup-config
            mountPath: /pulsar-metadata-tool/conf/pulsar-metadata-tool
          {{- include "pulsar.toolset.certs.volumeMounts" . | nindent 10 }}
      {{- end }}
      # This initContainer will wait for bookkeeper initnewcluster to complete
      # before initializing pulsar metadata
      - name: pulsar-bookkeeper-verify-clusterid
        image: "{{ .Values.images.pulsar_metadata.repository }}:{{ .Values.images.pulsar_metadata.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar_metadata.pullPolicy }}
        command: ["sh", "-c"]
        args:
        - >
          bin/apply-config-from-env.py conf/bookkeeper.conf;
          {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 10 }}
          until bin/bookkeeper shell whatisinstanceid; do
            sleep 3;
          done;
        envFrom:
        - configMapRef:
            name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}"
        volumeMounts:
        {{- include "pulsar.toolset.certs.volumeMounts" . | nindent 8 }}
      containers:
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
        image: "{{ .Values.images.pulsar_metadata.repository }}:{{ .Values.images.pulsar_metadata.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar_metadata.pullPolicy }}
      {{- if .Values.pulsar_metadata.resources }}
        resources:
{{ toYaml .Values.pulsar_metadata.resources | indent 10 }}
      {{- end }}
        command: ["sh", "-c"]
        args:
          - >
            {{- include "pulsar.toolset.zookeeper.tls.settings" . | nindent 12 }}
            bin/pulsar initialize-cluster-metadata \
              --cluster {{ template "pulsar.cluster" . }} \
              --zookeeper {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
              {{- if .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ .Values.pulsar_metadata.configurationStore }}{{ .Values.pulsar_metadata.configurationStoreMetadataPrefix }} \
              {{- end }}
              {{- if not .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ template "pulsar.zookeeper.connect" . }}{{ .Values.metadataPrefix }} \
              {{- end }}
              --web-service-url http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.cluster.local:8080/ \
              --web-service-url-tls https://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.cluster.local:8443/ \
              --broker-service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.cluster.local:6650/ \
              --broker-service-url-tls pulsar+ssl://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ template "pulsar.namespace" . }}.svc.cluster.local:6651/ || true;
        volumeMounts:
        {{- include "pulsar.toolset.certs.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "pulsar.toolset.certs.volumes" . | nindent 6 }}
      {{- if .Values.zookeeper.customTools.restore.enable }}
      - name: cleanup-config
        configMap:
          name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.customTools.restore.component }}"
      {{- end }}
      restartPolicy: Never
{{- end }}
{{- end }}
