#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#

# Based on the defult values, disable the vault component and auth
auth:
  authentication:
    enabled: false
  authorization:
    enabled: false
proxy:
  authenticateMetricsEndpoint:
    enabled: false