#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.monitoring.prometheus }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.prometheus.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.prometheus.component }}
data:
  # Include prometheus configuration file, setup to monitor all the
  # Kubernetes pods with the "scrape=true" annotation.
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
{{- if .Values.monitoring.alert_manager }}
    rule_files:
      - 'rules.yml'
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['{{ template "pulsar.fullname" . }}-{{ .Values.alert_manager.component }}:{{ .Values.alert_manager.port }}']
        path_prefix: {{ template "pulsar.control_center_path.alertmanager" . }}/
{{- end }}
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets:
        - '127.0.0.1:{{ .Values.prometheus.port }}'
      metrics_path: {{ template "pulsar.control_center_path.prometheus" . }}/metrics
    - job_name: 'kubernetes-pods'
{{- if .Values.auth.authentication.enabled }}
{{- if eq .Values.auth.authentication.provider "jwt" }}
      bearer_token_file: /pulsar/tokens/client/token
{{- end }}
{{- end }}
{{- if .Values.prometheus.sampleLimit }}
      sample_limit: {{ .Values.prometheus.sampleLimit }}
{{- end }}
      kubernetes_sd_configs:
      - role: pod
{{- if or .Values.istio.enabled (not .Values.prometheus.serviceAccount.clusterRole) }}
        namespaces:
          names:
            - {{ template "pulsar.namespace" . }}
{{- end }}
{{- if .Values.istio.enabled }}
      scheme: https
      # Disable http2 for Prometheus issue: https://github.com/prometheus/prometheus/issues/10213
      enable_http2: false
      tls_config:
        ca_file: /etc/prom-certs/root-cert.pem
        cert_file: /etc/prom-certs/cert-chain.pem
        key_file: /etc/prom-certs/key.pem
        insecure_skip_verify: true
{{- end }}
      relabel_configs:
{{- if .Values.istio.enabled }}
      # ignore job generated pod
      - source_labels: [__meta_kubernetes_pod_label_job_name]
        action: drop
        regex: ".+"
      # ignore prometheus,grafana,toolset,console
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: drop
        regex: "{{ .Values.prometheus.component }}|{{ .Values.grafana.component }}|{{ .Values.toolset.component }}|{{ .Values.streamnative_console.component }}"
{{- end }}
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: replace
        target_label: job
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      metric_relabel_configs:
{{- if .Values.prometheus.customRelabelConfigs -}}
{{- with .Values.prometheus.customRelabelConfigs }}
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}
{{- if and (eq .Values.prometheus.serviceAccount.clusterRole true) (ne .Values.istio.enabled true) }}
    - job_name: 'kubernetes-nodes'
      scheme: https
      kubernetes_sd_configs:
        - role: node

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics
    - job_name: 'kubernetes-cadvisor'
      scheme: https
      kubernetes_sd_configs:
        - role: node

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
{{- end }}
{{- if .Values.prometheus.extraScrapeConfigs -}}
{{- with .Values.prometheus.extraScrapeConfigs }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  rules.yml: |
{{- if .Values.monitoring.alert_manager -}}
{{- with .Values.alert_manager.rules }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
