#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.bookkeeper }}
{{- if and .Values.volumes.persistence .Values.bookkeeper.volumes.persistence }}
{{- if and (not (and .Values.volumes.local_storage .Values.bookkeeper.volumes.journal.local_storage)) .Values.bookkeeper.volumes.journal.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}-{{ .Values.bookkeeper.volumes.journal.name }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.bookkeeper.component }}
provisioner: {{ .Values.bookkeeper.volumes.journal.storageClass.provisioner }}
{{- if .Values.bookkeeper.volumes.journal.storageClass.volumeBindingMode }}
volumeBindingMode: {{ .Values.bookkeeper.volumes.journal.storageClass.volumeBindingMode }}
{{- end }}
{{- if .Values.bookkeeper.volumes.journal.storageClass.reclaimPolicy }}
reclaimPolicy: {{ .Values.bookkeeper.volumes.journal.storageClass.reclaimPolicy }}
{{- end }}
{{- if .Values.bookkeeper.volumes.journal.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.bookkeeper.volumes.journal.storageClass.allowVolumeExpansion }}
{{- end }}
{{- if .Values.bookkeeper.volumes.journal.storageClass.mountOptions }}
mountOptions:
{{- with .Values.bookkeeper.volumes.journal.storageClass.mountOptions }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- if .Values.bookkeeper.volumes.journal.storageClass.allowedTopologies }}
allowedTopologies:
{{- with .Values.bookkeeper.volumes.journal.storageClass.allowedTopologies }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
parameters:
  type: {{ .Values.bookkeeper.volumes.journal.storageClass.type }}
  fsType: {{ .Values.bookkeeper.volumes.journal.storageClass.fsType }}
{{- with .Values.bookkeeper.volumes.journal.storageClass.extraParameters }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
---

{{- if and (not (and .Values.volumes.local_storage .Values.bookkeeper.volumes.journal.local_storage)) .Values.bookkeeper.volumes.ledgers.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.bookkeeper.component }}-{{ .Values.bookkeeper.volumes.ledgers.name }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.bookkeeper.component }}
provisioner: {{ .Values.bookkeeper.volumes.ledgers.storageClass.provisioner }}
{{- if .Values.bookkeeper.volumes.ledgers.storageClass.volumeBindingMode }}
volumeBindingMode: {{ .Values.bookkeeper.volumes.ledgers.storageClass.volumeBindingMode }}
{{- end }}
{{- if .Values.bookkeeper.volumes.ledgers.storageClass.reclaimPolicy }}
reclaimPolicy: {{ .Values.bookkeeper.volumes.ledgers.storageClass.reclaimPolicy }}
{{- end }}
{{- if .Values.bookkeeper.volumes.ledgers.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.bookkeeper.volumes.ledgers.storageClass.allowVolumeExpansion }}
{{- end }}
{{- if .Values.bookkeeper.volumes.ledgers.storageClass.mountOptions }}
mountOptions:
{{- with .Values.bookkeeper.volumes.ledgers.storageClass.mountOptions }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- if .Values.bookkeeper.volumes.ledgers.storageClass.allowedTopologies }}
allowedTopologies:
{{- with .Values.bookkeeper.volumes.ledgers.storageClass.allowedTopologies }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
parameters:
  type: {{ .Values.bookkeeper.volumes.ledgers.storageClass.type }}
  fsType: {{ .Values.bookkeeper.volumes.ledgers.storageClass.fsType }}
{{- with .Values.bookkeeper.volumes.ledgers.storageClass.extraParameters }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
