#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: v2
appVersion: "0.0.1"
description: StreamNative Platform Stack
name: sn-platform-stack
version: 0.0.1
home: https://streamnative.io
sources:
- https://github.com/streamnative/charts/tree/master/charts/sn-platform
icon: https://streamnative.io/static/images/platform/sn-platform-header-element.svg
maintainers:
- name: StreamNative Support
  email: support@streamnative.io
dependencies:
- name: sn-platform-vault
  version: 0.0.1
  repository: file://../sn-platform-vault
- name: sn-platform-presto
  version: 0.0.1
  repository: file://../sn-platform-presto
- name: sn-platform
  version: 2.0.0
  repository: file://../sn-platform
- name: pulsar-detector
  version: 0.0.1
  repository: file://../pulsar-detector
- name: sn-console
  version: 1.9
  repository: file://../sn-console
