#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

global:
  stackName: "<stack-name>"
  stackVersion: "0.1.0"
  
sn-platform:
  # Flag to control whether to run initialize job
  initialize: false

  ## Components
  ##
  ## Control what components of Apache Pulsar to deploy for the cluster
  components:
    # streamnative console
    streamnative_console: false
    pulsar_detector: false
    vault: false
    sql_worker: false

sn-console:
  enabled: true
  initialize: false
  # broker related settings. configure how streamnative console should access Pulsar brokers.
  broker:
    webServiceUrl: http://localhost:8080
    # kopServiceUrl: localhost:9093
    auth:
      authentication:
        vault:
          secretKeyRef: ""
  volumes:
    data:
      storageClassName: ""
  streamnative_console:
    configData:
      # *required*: the organization name to show in the SN console
      DEFAULT_ORGANIZATION: "streamnative"
      # *required*: the instance name to display for the Pulsar clusters in SN console
      INSTANCE_NAME: "pulsar"
      GLOBAL_RESOURCE_READ_ONLY: false
    login:
      sso:
        google:
          enabled: false
        azure:
          enabled: false
        okta:
          enabled: false
  # vault
  vault:
    # vault service url
    url: http://localhost:8200
    # Flag to control whether to start a job to initialize vault for OIDC authentication
    # The initialize job will create the following secrets:
    # - A secret that contains vault secrets used for configuring the SN console
    # - A secret that contains the password for user `admin` for the SN console
    # - A toolset token to store in the secret `vault.toolsetTokenSecretRef`
    initialize: false
      
sn-platform-vault:
  enabled: true
  fullnameOverride: "<stack-name>-sn-platform"
  images:
    broker:
      repository: streamnative/sn-platform
      tag: "2.9.2.17"
      pullPolicy: IfNotPresent

sn-platform-detector:
  enabled: false
  images:
    broker:
      repository: streamnative/sn-platform
      tag: "2.9.2.17"
      pullPolicy: IfNotPresent
  pulsar_detector:
    clusterName: ""
    zookeeper:
      url: ""
    broker:
      clientSecretName: ""
      service: ""
      serviceURL: ""
      webserviceURL: ""
      
sn-platform-presto:
  enabled: true
  zkURL: localhost:2181
  images:
    presto:
      repository: streamnative/sn-platform
      tag: "2.9.2.17"
      pullPolicy: IfNotPresent
  service:
    spec:
      clusterIP: None
  coordinator:
    config:
      http:
        port: 8081
      # Add custom configs to config.properties
      pulsarExtraConfig: |
        pulsar.broker-service-url=http://localhost:8080
  worker:
    service:
      spec:
        clusterIP: None
    config:
      # Add custom configs to config.properties
      pulsarExtraConfig: |
        pulsar.broker-service-url=http://localhost:8080
