#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#

{{- if .Values.components.bookkeeper }}
{{- if and .Values.volumes.persistence .Values.bookkeeper.volumes.persistence }}
{{- if .Values.bookkeeper.volumes.journal.volumeAttributesClass }}
apiVersion: storage.k8s.io/v1alpha1
kind: VolumeAttributesClass
metadata:
  name: "{{ template "pulsar.bookkeeper.journal.volumeAttributesClassName" . }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.bookkeeper.component }}
driverName: {{ .Values.bookkeeper.volumes.journal.volumeAttributesClass.driverName }}
{{- if .Values.bookkeeper.volumes.journal.volumeAttributesClass.parameters }}
parameters:
{{- with .Values.bookkeeper.volumes.journal.volumeAttributesClass.parameters }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
---

{{- if .Values.bookkeeper.volumes.ledgers.volumeAttributesClass }}
apiVersion: storage.k8s.io/v1alpha1
kind: VolumeAttributesClass
metadata:
  name: "{{ template "pulsar.bookkeeper.ledgers.volumeAttributesClassName" . }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.bookkeeper.component }}
driverName: {{ .Values.bookkeeper.volumes.ledgers.volumeAttributesClass.driverName }}
{{- if .Values.bookkeeper.volumes.ledgers.volumeAttributesClass.parameters }}
parameters:
{{- with .Values.bookkeeper.volumes.ledgers.volumeAttributesClass.parameters }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}

