#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#

apiVersion: v1
appVersion: "3.0.0"
description: StreamNative Platform Chart
name: sn-platform
version: 1.11.31
home: https://streamnative.io
sources:
- https://github.com/streamnative/charts/tree/master/charts/sn-platform
icon: https://raw.githubusercontent.com/streamnative/charts/master/static/logo.svg
maintainers:
- name: StreamNative Support
  email: support@streamnative.io
