#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#

dependencies:
- name: loki
  version: 0.31.1
  repository: https://grafana.github.io/helm-charts
  condition: monitoring.loki
#- name: superset
#  version: 0.1.1
#  repository:  https://apache.github.io/superset
#  condition: components.superset