{{- if .Values.components.streamnative_console }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.streamnative_console.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.streamnative_console.component }}
  annotations:
{{ toYaml .Values.streamnative_console.service.annotations | indent 4 }}
spec:
{{- if .Values.streamnative_console.service.type }}
  type: {{ .Values.streamnative_console.service.type }}
{{- else }}
  clusterIP: None
{{- end }}
{{- with .Values.streamnative_console.service.spec }}
{{ toYaml . | indent 2 }}
{{- end }}
  ports:
    - name: frontend
      port: {{ .Values.streamnative_console.service.ports.frontend }}
      protocol: TCP
      targetPort: 9527
    - name: backend
      port: {{ .Values.streamnative_console.service.ports.backend }}
      protocol: TCP
      targetPort: 7750
  selector:
    app: {{ template "pulsar.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.streamnative_console.component }}
{{- end }}
