{{- if and .Values.components.streamnative_console .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.streamnative_console.component }}"
  namespace: {{ template "pulsar.namespace" . }}
spec:
  rules:
  - to:
    - operation:
        ports:
        - "7750"
        - "9527"
  action: ALLOW
  selector:
    matchLabels:
      app: {{ template "pulsar.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.streamnative_console.component }}
{{- end }}