apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "pulsar-resources-operator.fullname" . }}-leader-election-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pulsar-resources-operator.roleLeaderElectionName" . }}
subjects:
- kind: ServiceAccount
  name : {{ include "pulsar-resources-operator.serviceAccountName" . }}
  namespace: {{ include "pulsar-resources-operator.namespace" .}}
