{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulsar-resources-operator.serviceAccountName" . }}
  namespace: {{ include "pulsar-resources-operator.namespace" .}}
  labels:
    {{- include "pulsar-resources-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
