apiVersion: v1
appVersion: "1.0.0"
description: Chart to deploy an image puller that pulls docker images
name: sn-image-puller
version: 1.0.0
home: https://streamnative.io
sources:
- https://github.com/streamnative/charts/pulsar
icon: http://pulsar.apache.org/img/pulsar.svg
maintainers:
- name: StreamNative Support
  email: support@streamnative.io
