charts:
  operator:
    targetRevision: 0.16.3
    releaseName: pulsar-operator
    releaseNamespace: sn-pulsar
  platform:
    targetRevision: 1.10.3
    releaseName: sn-platform
    releaseNamespace: sn-pulsar

values:
  repoUrl: https://github.com/streamnative/charts
  path: examples/argocd/values
  targetRevision: master

destination:
  server: https://kubernetes.default.svc