#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if and .Values.components.functions .Values.functions.useDedicatedRunner }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.functions.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.functions.component }}
spec:
  serviceName: "{{ template "pulsar.fullname" . }}-{{ .Values.functions.component }}"
  replicas: {{ .Values.functions.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
      component: {{ .Values.functions.component }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        {{- include "pulsar.template.labels" . | nindent 8 }}
        component: {{ .Values.functions.component }}
{{- if or (and .Values.prometheus.scrape.function_worker .Values.prometheus.scrape.enabled) .Values.functions.autoRollDeployment .Values.functions.annotations }}
      annotations:
{{- if (and .Values.prometheus.scrape.function_worker .Values.prometheus.scrape.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.functions.ports.http }}"
{{- end }}
        {{- include "pulsar.istio.pod.annotations" . | nindent 8 }}
        {{- if .Values.functions.autoRollDeployment }}
        checksum/config: {{ include (print $.Template.BasePath "/broker/function-worker-configfile-configmap.yaml") . | sha256sum }}
    {{- end }}
{{- with .Values.functions.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      securityContext:
{{- with .Values.functions.securityContext }}
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if or .Values.functions.serviceAccount.use (and .Values.components.functions  (not .Values.functions.useDedicatedRunner)) }}
      serviceAccountName: {{ template "pulsar.function.serviceAccount" . }}
      {{- end }}
      {{- if .Values.functions.nodeSelector }}
      nodeSelector: {{- toYaml .Values.functions.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.functions.tolerations }}
      tolerations: {{- toYaml .Values.functions.tolerations | nindent 8 }}
      {{- end }}
      affinity:
        {{- include "pulsar.antiAffinityRules" (dict "Values" .Values "thisAffinity" .Values.functions.affinity "Component" .Values.functions.component "Release" .Release "Chart" .Chart) | indent 8 }}
      terminationGracePeriodSeconds: {{ .Values.functions.gracePeriod }}
      initContainers:
      {{- if and .Values.components.proxy (not .Values.istio.enabled) }}
        # This init container will wait for pulsar proxy to be ready before deploying the function worker
        - name: wait-proxy-ready
          image: "{{ .Values.images.function_worker.repository }}:{{ .Values.images.function_worker.tag }}"
          imagePullPolicy: {{ .Values.images.function_worker.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - >-
              set -e;
              proxyServiceNumber="$(nslookup -timeout=10 {{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }} | grep Name | wc -l)";
              until [ ${proxyServiceNumber} -ge 1 ]; do
                echo "pulsar proxy {{ template "pulsar.fullname" . }} isn't initialized yet ... check in 10 seconds ...";
                sleep 10;
                proxyServiceNumber="$(nslookup -timeout=10 {{ template "pulsar.fullname" . }}-{{ .Values.proxy.component }} | grep Name | wc -l)";
              done;
          {{- if .Values.functions.resources }}
          resources: {{- toYaml .Values.functions.resources | nindent 12 }}
          {{- end }}
      {{- end }}
{{- with .Values.common.extraInitContainers }}
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: "{{ template "pulsar.fullname" . }}-{{ .Values.functions.component }}"
          image: "{{ .Values.images.function_worker.repository }}:{{ .Values.images.function_worker.tag }}"
          imagePullPolicy: {{ .Values.images.function_worker.pullPolicy }}
          {{- if .Values.functions.probe.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /initialized
              port: {{ .Values.functions.ports.http }}
            initialDelaySeconds: {{ .Values.functions.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.functions.probe.liveness.periodSeconds }}
            failureThreshold: {{ .Values.functions.probe.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.functions.probe.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /initialized
              port: {{ .Values.functions.ports.http }}
            initialDelaySeconds: {{ .Values.functions.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.functions.probe.readiness.periodSeconds }}
            failureThreshold: {{ .Values.functions.probe.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.functions.resources }}
          resources:
{{ toYaml .Values.functions.resources | indent 12 }}
          {{- end }}
          command: ["sh", "-c"]
          args:
            - >
              bin/pulsar functions-worker;
          ports:
            # prometheus needs to access /metrics endpoint
            - name: http
              containerPort: {{ .Values.functions.ports.http }}
            {{- if and .Values.tls.enabled .Values.tls.functions.enabled }}
            - name: https
              containerPort: {{ .Values.functions.ports.https }}
            {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- with .Values.functions.extraEnvs }}
{{ toYaml . | indent 12 }}
{{- end }}
          volumeMounts:
          {{- include "pulsar.function.worker.config.volumeMounts" . | nindent 10 }}
          {{- include "pulsar.function.token.volumeMounts" . | nindent 10 }}
          {{- include "pulsar.function.certs.volumeMounts" . | nindent 10 }}
{{- with .Values.functions.extraVolumeMounts }}
{{ toYaml . | indent 10 }}
{{- end }}
      volumes:
      {{- include "pulsar.function.worker.config.volumes" . | nindent 6 }}
      {{- include "pulsar.function.token.volumes" . | nindent 6 }}
      {{- include "pulsar.function.certs.volumes" . | nindent 6 }}
{{- with .Values.functions.extraVolumes }}
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}
