#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.ingress.control_center.enabled }}
{{- $fullName := include "pulsar.fullname" . -}}

{{/* COMMENT */}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.ingress.control_center.component }}-ingress"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
  annotations:
{{- if and .Values.ingress.control_center.tls.enabled (not .Values.ingress.controller.tls.termination) }}
    # don't do ssl-redirect if ssl is already terminated at the load balancer level
    ingress.kubernetes.io/ssl-redirect: "true"
{{- if and .Values.certs.public_issuer.enabled }}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "{{ template "pulsar.fullname" . }}-{{ .Values.certs.public_issuer.component }}"
{{- end }}
{{- else }}
    ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
    kubernetes.io/ingress.class: nginx
  {{- with .Values.ingress.control_center.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and .Values.ingress.control_center.tls.enabled (not .Values.ingress.controller.tls.termination) }}
  {{- if .Values.external_dns.domain_filter }}
  tls:
    - hosts:
        - {{ printf "admin.%s.%s" .Release.Name .Values.external_dns.domain_filter }}
      secretName: {{ template "pulsar.fullname" . }}-{{ .Values.ingress.control_center.component }}-ingress
  {{- end }}
{{- end }}
  rules:
    - host: {{ template "pulsar.control_center_domain" . }}
      http:
        paths:
          {{- if and .Values.monitoring.grafana .Values.ingress.control_center.endpoints.grafana }}
          - path: /grafana
            backend:
              serviceName: "{{ $fullName }}-{{ .Values.grafana.component }}"
              servicePort: {{ .Values.grafana.port }}
          {{- end }}
          {{- if and .Values.monitoring.alert_manager .Values.ingress.control_center.endpoints.alertmanager }}
          - path: /alerts
            backend:
              serviceName: "{{ $fullName }}-{{ .Values.alert_manager.component }}"
              servicePort: {{ .Values.alert_manager.port }}
          {{- end }}
          {{- if and .Values.monitoring.prometheus .Values.ingress.control_center.endpoints.prometheus }}
          - path: /prometheus
            backend:
              serviceName: "{{ $fullName }}-{{ .Values.prometheus.component }}"
              servicePort: {{ .Values.prometheus.port }}
          {{- end }}
          {{- if .Values.components.pulsar_manager }}
          - path: /
            backend:
              serviceName: "{{ $fullName }}-{{ .Values.pulsar_manager.component }}"
              servicePort: {{ .Values.pulsar_manager.ports.frontend }}
          {{- end }}
{{- end }}
