{{- if .Values.monitoring.prometheus }}
{{- if and .Values.volumes.persistence .Values.prometheus.volumes.persistence }}
{{- if .Values.prometheus.volumes.data.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.prometheus.component }}-{{ .Values.prometheus.volumes.data.name }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.prometheus.component }}
provisioner: {{ .Values.prometheus.volumes.data.storageClass.provisioner }}
parameters:
  type: {{ .Values.prometheus.volumes.data.storageClass.type }}
  fsType: {{ .Values.prometheus.volumes.data.storageClass.fsType }}
{{- if .Values.prometheus.volumes.data.storageClass.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.prometheus.volumes.data.storageClass.allowVolumeExpansion }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
