{{- if .Values.components.streamnative_console }}
{{- if and .Values.volumes.persistence .Values.streamnative_console.volumes.persistence }}
{{- if not (or .Values.streamnative_console.volumes.data.storageClass .Values.streamnative_console.volumes.data.storageClassName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "pulsar.streamnative_console.data.pvc.name" . }}"
  namespace: {{ template "pulsar.namespace" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.streamnative_console.volumes.data.size }}
  accessModes: [ "ReadWriteOnce" ]
{{- if  .Values.streamnative_console.volumes.data.storageClass }}
  storageClassName: "{{ template "pulsar.streamnative_console.data.pvc.name" . }}"
{{- else if .Values.streamnative_console.volumes.data.storageClassName }}
  storageClassName: {{ .Values.streamnative_console.volumes.data.storageClassName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
