# deploy zookeeper only when `zookeeper.customTools.backup.enable` is true
{{- if .Values.zookeeper.customTools.backup.enable }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.customTools.backup.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.zookeeper.component }}
  annotations:
{{ toYaml .Values.zookeeper.service.annotations | indent 4 }}
spec:
  ports:
    - name: client
      port: {{ .Values.zookeeper.ports.client }}
    {{- if and .Values.tls.enabled .Values.tls.zookeeper.enabled }}
    - name: client-tls
      port: {{ .Values.zookeeper.ports.clientTls }}
    {{- end }}
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "pulsar.matchLabels" . | nindent 4 }}
    component: {{ .Values.zookeeper.customTools.backup.component }}
{{- end }}
