#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- /*
Returns an image-puller daemonset. Two daemonsets will be created like this.
- hook-image-puller: for pre helm upgrade image pulling (lives temporarily)
- continuous-image-puller: for newly added nodes image pulling
*/}}
{{- define "pulsar.imagePuller.daemonset" -}}
# image puller daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "pulsar.fullname" . }}-{{ print .componentPrefix "image-puller" }}
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
  {{- if .hook }}
  annotations:
    {{- /*
    Allows the daemonset to be deleted when the image-awaiter job is completed.
    */}}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pulsar.matchLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the DaemonSet to restart the pods. */}}
        {{- include "pulsar.template.labels" . | nindent 8 }}
    spec:
      initContainers:
        {{- with .Values.images }}
        - name: image-pull-zookeeper
          image: {{ .zookeeper.repository }}:{{ .zookeeper.tag }}
          imagePullPolicy: {{ .zookeeper.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-bookie
          image: {{ .bookie.repository }}:{{ .bookie.tag }}
          imagePullPolicy: {{ .bookie.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-presto
          image: {{ .presto.repository }}:{{ .presto.tag }}
          imagePullPolicy: {{ .presto.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-autorecovery
          image: {{ .autorecovery.repository }}:{{ .autorecovery.tag }}
          imagePullPolicy: {{ .autorecovery.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-broker
          image: {{ .broker.repository }}:{{ .broker.tag }}
          imagePullPolicy: {{ .broker.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-proxy
          image: {{ .proxy.repository }}:{{ .proxy.tag }}
          imagePullPolicy: {{ .proxy.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-functions
          image: {{ .functions.repository }}:{{ .functions.tag }}
          imagePullPolicy: {{ .functions.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-prometheus
          image: {{ .prometheus.repository }}:{{ .prometheus.tag }}
          imagePullPolicy: {{ .prometheus.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-alert-manager
          image: {{ .alert_manager.repository }}:{{ .alert_manager.tag }}
          imagePullPolicy: {{ .alert_manager.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-grafana
          image: {{ .grafana.repository }}:{{ .grafana.tag }}
          imagePullPolicy: {{ .grafana.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-pulsar-manager
          image: {{ .pulsar_manager.repository }}:{{ .pulsar_manager.tag }}
          imagePullPolicy: {{ .pulsar_manager.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-node-exporter
          image: {{ .node_exporter.repository }}:{{ .node_exporter.tag }}
          imagePullPolicy: {{ .node_exporter.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        - name: image-pull-nginx-ingress-controller
          image: {{ .nginx_ingress_controller.repository }}:{{ .nginx_ingress_controller.tag }}
          imagePullPolicy: {{ .nginx_ingress_controller.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - echo "Pulling complete"
        {{- end }}
      containers:
        - name: pause
          image: {{ .Values.imagePuller.pause.image.name }}:{{ .Values.imagePuller.pause.image.tag }}
{{- end }}
