#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.broker }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "pulsar.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.pulsar_metadata.component }}
    cluster: {{ template "pulsar.fullname" . }}
spec:
  template:
    spec:
      initContainers:
      - name: wait-zookeeper-ready
        image: "{{ .Values.images.pulsar.repository }}:{{ .Values.images.pulsar.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar.pullPolicy }}
        command: ["sh", "-c"]
        args:
          - >-
            until nslookup {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}-{{ add (.Values.zookeeper.replicaCount | int) -1 }}.{{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}.{{ .Values.namespace }}; do
              sleep 3;
            done;
      # This initContainer will wait for bookkeeper initnewcluster to complete
      # before initializing pulsar metadata
      - name: pulsar-bookkeeper-verify-clusterid
        image: "{{ .Values.images.pulsar.repository }}:{{ .Values.images.pulsar.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar.pullPolicy }}
        command: ["sh", "-c"]
        args:
        - >
          {{ .Values.exacutableDir }}apply-config-from-env.py {{ .Values.confDir }}bookkeeper.conf &&
          until {{ .Values.exacutableDir }}bookkeeper shell whatisinstanceid; do
            sleep 3;
          done;
        envFrom:
        - configMapRef:
            name: "{{ template "pulsar.fullname" . }}-{{ .Values.toolset.component }}"
      containers:
      - name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_metadata.component }}"
        image: "{{ .Values.images.pulsar.repository }}:{{ .Values.images.pulsar.tag }}"
        imagePullPolicy: {{ .Values.images.pulsar.pullPolicy }}
      {{- if .Values.pulsar_metadata.resources }}
        resources:
{{ toYaml .Values.pulsar_metadata.resources | indent 10 }}
      {{- end }}
        command: ["sh", "-c"]
        args:
          - >
            {{ .Values.exacutableDir }}pulsar initialize-cluster-metadata \
              --cluster {{ template "pulsar.fullname" . }} \
              --zookeeper {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}{{ .Values.metadataPrefix }} \
              {{- if .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ .Values.pulsar_metadata.configurationStore }} \
              {{- end }}
              {{- if not .Values.pulsar_metadata.configurationStore }}
              --configuration-store {{ template "pulsar.fullname" . }}-{{ .Values.zookeeper.component }}{{ .Values.metadataPrefix }} \
              {{- end }}
              --web-service-url http://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ .Values.namespace }}.svc.cluster.local:8080/ \
              --web-service-url-tls https://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ .Values.namespace }}.svc.cluster.local:8443/ \
              --broker-service-url pulsar://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ .Values.namespace }}.svc.cluster.local:6650/ \
              --broker-service-url-tls pulsar+ssl://{{ template "pulsar.fullname" . }}-{{ .Values.broker.component }}.{{ .Values.namespace }}.svc.cluster.local:6651/ || true;
      restartPolicy: Never
{{- end }}
