#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#
{{- if and .Values.initialize .Values.auth.authentication.enabled .Values.auth.authentication.jwt.enabled .Values.auth.authentication.jwt.autoInitSecret }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "pulsar.fullname" . }}-jwt-secret-init-acct
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pulsar.fullname" . }}-jwt-secret-init-acct-role
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list","watch" ,"get" ,"update" ,"create" ,"delete" ,"patch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pulsar.fullname" . }}-jwt-secret-init-acct-rolebinding
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "pulsar.fullname" . }}-jwt-secret-init-acct-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "pulsar.fullname" . }}-jwt-secret-init-acct
    namespace: {{ template "pulsar.namespace" . }}

{{- end }}
