#
# Copyright (c) 2019 - 2024 StreamNative, Inc.. All Rights Reserved.
#
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: brokers
  namespace: default
spec:
  image: streamnative/sn-platform-slim:2.10.5.3
  # The field logConfig can be used to change the log level and log format of pods.
  # The logConfig field is optional. If it is not specified, the component will use the default log configuration /pulsar/conf/log4j2.yaml.
  # If it is specified will dynamically change the log level and log format of the component by changing the CR.
  logConfig:
  # The level field can be used to change the log level of the component. The value can be one of TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF.
    level: DEBUG
   # The format field can be used to change the log format of the component. The value can be one of json, text.
    format: json
  # The template field can totally change the log config of the component. The value is a string, which is the content of the log config file.
    template: |
      Configuration:
        status: INFO
        monitorInterval: 30
        name: pulsar
        packages: io.prometheus.client.log4j2

        Properties:
          Property:
            - name: "pulsar.log.dir"
              value: "logs"
            - name: "pulsar.log.file"
              value: "pulsar.log"
            - name: "pulsar.log.immediateFlush"
              value: "false"
            - name: "pulsar.log.appender"
              value: "RoutingAppender"
            - name: "pulsar.log.root.level"
              value: "info"
            - name: "pulsar.log.level"
              value: "info"
            - name: "pulsar.routing.appender.default"
              value: "Console"

  pod:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
  replicas: 2
  zkServers: zookeepers-zk:2181
