#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.components.sql_worker }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "presto.coordinator" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
data:
  node.properties: |
    node.environment={{ .Values.presto.server.node.environment }}
    node.data-dir={{ .Values.presto.server.node.dataDir }}
  jvm.config: |
    -server
    -Xmx{{ .Values.presto.server.jvm.maxHeapSize }}
    -XX:+{{ .Values.presto.server.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.presto.server.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
  config.properties: |
    #
    # Licensed to the Apache Software Foundation (ASF) under one
    # or more contributor license agreements.  See the NOTICE file
    # distributed with this work for additional information
    # regarding copyright ownership.  The ASF licenses this file
    # to you under the Apache License, Version 2.0 (the
    # "License"); you may not use this file except in compliance
    # with the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing,
    # software distributed under the License is distributed on an
    # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    # KIND, either express or implied.  See the License for the
    # specific language governing permissions and limitations
    # under the License.
    #

    coordinator=true
    http-server.http.port={{ .Values.presto.server.config.http.port }}
    discovery-server.enabled=true
    discovery.uri=http://{{ template "presto.fullname" . }}:{{ .Values.presto.server.config.http.port }}
    query.max-memory=50GB
    query.max-memory-per-node=1GB
    distributed-joins-enabled=true
{{- if gt (int .Values.presto.server.workers) 0 }}
    node-scheduler.include-coordinator=false
{{- else }}
    node-scheduler.include-coordinator=true
{{- end }}

  log.properties: |
    #
    # Licensed to the Apache Software Foundation (ASF) under one
    # or more contributor license agreements.  See the NOTICE file
    # distributed with this work for additional information
    # regarding copyright ownership.  The ASF licenses this file
    # to you under the Apache License, Version 2.0 (the
    # "License"); you may not use this file except in compliance
    # with the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing,
    # software distributed under the License is distributed on an
    # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    # KIND, either express or implied.  See the License for the
    # specific language governing permissions and limitations
    # under the License.
    #

    com.facebook.presto={{ .Values.presto.server.log.presto.level }}
    com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory=WARN
    com.ning.http.client=WARN
    com.facebook.presto.server.PluginManager={{ .Values.presto.server.log.presto.level }}
  
  pulsar.properties: |
    #
    # Licensed to the Apache Software Foundation (ASF) under one
    # or more contributor license agreements.  See the NOTICE file
    # distributed with this work for additional information
    # regarding copyright ownership.  The ASF licenses this file
    # to you under the Apache License, Version 2.0 (the
    # "License"); you may not use this file except in compliance
    # with the License.  You may obtain a copy of the License at
    #
    #   http://www.apache.org/licenses/LICENSE-2.0
    #
    # Unless required by applicable law or agreed to in writing,
    # software distributed under the License is distributed on an
    # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    # KIND, either express or implied.  See the License for the
    # specific language governing permissions and limitations
    # under the License.
    
    
    # name of the connector to be displayed in the catalog
    connector.name=pulsar
    # the url of Pulsar broker service
    pulsar.broker-service-url={{ .Values.presto.server.brokers }}
    # pulsar.broker-service-url={{ .Values.presto.server.brokers }}
    # URI of Zookeeper cluster
    pulsar.zookeeper-uri={{ .Values.presto.server.zookeepers }}
    # minimum number of entries to read at a single time
    pulsar.max-entry-read-batch-size=100
    # default number of splits to use per query
    pulsar.target-num-splits=2
    # max message queue size
    pulsar.max-split-message-queue-size=10000
    # max entry queue size
    pulsar.max-split-entry-queue-size=1000
    # Rewrite namespace delimiter
    # Warn: avoid using symbols allowed by Namespace (a-zA-Z_0-9 -=:%)
    # to prevent erroneous rewriting
    pulsar.namespace-delimiter-rewrite-enable=false
    pulsar.rewrite-namespace-delimiter=/
    
    
    ####### TIERED STORAGE OFFLOADER CONFIGS #######
    
    ## Driver to use to offload old data to long term storage
    #pulsar.managed-ledger-offload-driver = aws-s3
    
    ## The directory to locate offloaders
    #pulsar.offloaders-directory = /pulsar/offloaders
    
    ## Maximum number of thread pool threads for ledger offloading
    #pulsar.managed-ledger-offload-max-threads = 2
    
    ## Properties and configurations related to specific offloader implementation
    #pulsar.offloader-properties = \
    #  {"s3ManagedLedgerOffloadBucket": "offload-bucket", \
    #  "s3ManagedLedgerOffloadRegion": "us-west-2", \
    #  "s3ManagedLedgerOffloadServiceEndpoint": "http://s3.amazonaws.com"}
    
    
    ####### AUTHENTICATION CONFIGS #######
    
    ## the authentication plugin to be used to authenticate to Pulsar cluster
    #pulsar.auth-plugin =
    
    ## the authentication parameter to be used to authenticate to Pulsar cluster
    #pulsar.auth-params =
    
    ## Accept untrusted TLS certificate
    #pulsar.tls-allow-insecure-connection =
    
    ## Whether to enable hostname verification on TLS connections
    #pulsar.tls-hostname-verification-enable =
    
    ## Path for the trusted TLS certificate file
    #pulsar.tls-trust-cert-file-path =
    
    ####### BOOKKEEPER CONFIGS #######
    
    # Entries read count throttling-limit per seconds, 0 is represents disable the throttle, default is 0.
    pulsar.bookkeeper-throttle-value = 0
    
    # The number of threads used by Netty to handle TCP connections,
    # default is 2 * Runtime.getRuntime().availableProcessors().
    # pulsar.bookkeeper-num-io-threads =
    
    # The number of worker threads used by bookkeeper client to submit operations,
    # default is Runtime.getRuntime().availableProcessors().
    # pulsar.bookkeeper-num-worker-threads =
    
    
    ####### MANAGED LEDGER CONFIGS #######
    
    # Amount of memory to use for caching data payload in managed ledger. This memory
    # is allocated from JVM direct memory and it's shared across all the managed ledgers
    # running in same sql worker. 0 is represents disable the cache, default is 0.
    pulsar.managed-ledger-cache-size-MB = 0
    
    # Number of threads to be used for managed ledger tasks dispatching,
    # default is Runtime.getRuntime().availableProcessors().
    # pulsar.managed-ledger-num-worker-threads =
    
    # Number of threads to be used for managed ledger scheduled tasks,
    # default is Runtime.getRuntime().availableProcessors().
    # pulsar.managed-ledger-num-scheduler-threads =

  docker-presto.sh: |
    #!/bin/bash 
    cp {{ .Values.presto.server.config.path }}/*.properties $PULSAR_HOME/conf/presto
    cp {{ .Values.presto.server.config.path }}/*.config $PULSAR_HOME/conf/presto
    cp {{ .Values.presto.server.config.path }}/pulsar.properties $PULSAR_HOME/conf/presto/catalog
    ./bin/pulsar sql-worker run --node-config=$PULSAR_HOME/conf/presto/node.properties --jvm-config=$PULSAR_HOME/conf/presto/jvm.config
{{- end }}
